spring:
  datasource:
    url: jdbc:mariadb://localhost:43306/example(fastlms)
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234


  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: tjddbs1412@gmail.com
    password: dmnuaxblhjubqufu
    properties:
      mail:
        smtp:
          starttls:
            enable: true


mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
